# Generated by Django 4.1.3 on 2022-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMiniModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.URLField()),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('enName', models.CharField(max_length=100, verbose_name='Имя по Английски')),
                ('enProfession', models.CharField(max_length=100, verbose_name='Профессия по Английски')),
            ],
        ),
    ]
